import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { getDatabase, hasDatabase } from "@/lib/database";

export type BlogPost = { id: string; slug: string; classId: string; title: string; content: string; authorId: string; imageUrl?: string; publishedAt: string };
type BlogRow = { id: string; slug: string; class_id: string; title: string; content: string; author_id: string; image_url: string | null; published_at: string };

function map(row: BlogRow): BlogPost { return { id: row.id, slug: row.slug, classId: row.class_id, title: row.title, content: row.content, authorId: row.author_id, imageUrl: row.image_url ?? undefined, publishedAt: row.published_at }; }
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 72) || "blog-post"; }
export async function getPublishedBlogPosts(): Promise<BlogPost[]> { if (!hasDatabase()) return []; const rows = await getDatabase()`SELECT id, slug, class_id, title, content, author_id, image_url, published_at FROM blog_posts WHERE status='published' AND deleted_at IS NULL ORDER BY published_at DESC`; return (rows as unknown as BlogRow[]).map(map); }
export async function getBlogPost(slug: string): Promise<BlogPost | undefined> { if (!hasDatabase()) return undefined; const rows = await getDatabase()`SELECT id, slug, class_id, title, content, author_id, image_url, published_at FROM blog_posts WHERE slug=${slug} AND status='published' AND deleted_at IS NULL LIMIT 1`; const row = (rows as unknown as BlogRow[])[0]; return row ? map(row) : undefined; }
export async function publishWebhookBlogPost(input: { classId: string; title: string; content: string; authorId: string; imageUrl?: string }): Promise<{ post: BlogPost; duplicate: boolean }> { const fingerprint = createHash("sha256").update([input.classId, input.title, input.content, input.authorId].join("\u0000")).digest("hex"); const sql = getDatabase(); const existing = await sql`SELECT id, slug, class_id, title, content, author_id, image_url, published_at FROM blog_posts WHERE source_fingerprint=${fingerprint} LIMIT 1` as unknown as BlogRow[]; if (existing.length) return { post: map(existing[0]), duplicate: true }; const slug = `${slugify(input.title)}-${randomUUID().slice(0, 8)}`; const rows = await sql`INSERT INTO blog_posts (slug, class_id, title, content, author_id, image_url, source_fingerprint) VALUES (${slug}, ${input.classId}, ${input.title}, ${input.content}, ${input.authorId}, ${input.imageUrl ?? null}, ${fingerprint}) RETURNING id, slug, class_id, title, content, author_id, image_url, published_at`; return { post: map((rows as unknown as BlogRow[])[0]), duplicate: false }; }
