import Image from "next/image";
import Link from "next/link";
import { ProductCard } from "@/components/product-card";
import { getPublishedProducts } from "@/lib/content-store";
export default async function Home() { const products = await getPublishedProducts(); return <>
  <section className="hero"><Image src="/images/africa-fire-pump-hero.png" alt="Concept visual of a fire-pump installation serving an African industrial project" fill priority sizes="100vw" className="hero-media" /><div className="hero-shade" /><div className="wrap hero-content"><p className="eyebrow light">GRIMM PUMP · AFRICA PROJECT DESK</p><h1>Fire water systems built for the conditions your project faces.</h1><p>Configured diesel, electric and jockey pump packages for industrial, commercial and infrastructure projects across Africa.</p><div className="hero-actions"><Link href="/contact" className="cta">Discuss your project →</Link><Link href="/products" className="ghost-link">View pump systems ↓</Link></div><div className="hero-facts"><span><b>EDJ · DJ · EJ</b>Complete package options</span><span><b>50–2500 GPM</b>Published range on main site</span><span><b>EN / FR</b>Business-language support</span></div></div></section>
  <section className="section intro"><div className="wrap two-column"><div><p className="eyebrow">AFRICA-FOCUSED, PROJECT-READY</p><h2>Start with the realities on site.</h2><p>We help project teams define a fire-pump package around water supply, power availability, duty/standby needs and the documentation required before shipment.</p><Link href="/contact" className="inline-link">Tell us your requirements →</Link></div><div className="number-list"><article><b>01</b><div><h3>Power-resilient options</h3><p>Electric, diesel and combined configurations for planned and backup operation.</p></div></article><article><b>02</b><div><h3>Project documentation</h3><p>Selection data, catalogues and testing information for engineering review.</p></div></article><article><b>03</b><div><h3>Direct export dialogue</h3><p>Discuss pump selection, delivery scope and your timeline with GRIMM sales.</p></div></article></div></div></section>
  <section className="section wrap"><div className="section-heading"><div><p className="eyebrow">PRODUCT SYSTEMS</p><h2>Choose the system, then configure the details.</h2></div><p>Core products from the GRIMM PUMP range, arranged for fire protection and water-management projects.</p></div><div className="product-grid">{products.slice(0, 3).map((product) => <ProductCard key={product.id} product={product} />)}</div><Link className="inline-link all-link" href="/products">Explore all products →</Link></section>
  <section className="section dark"><div className="wrap applications"><div><p className="eyebrow gold">APPLICATIONS</p><h2>Built around project conditions, not catalogue pages.</h2><p>Start a procurement conversation with the risk, operating conditions and application your site needs to address.</p><Link href="/applications" className="cta outline">Explore applications →</Link></div><div className="application-grid">{[["01", "Logistics & warehousing", "Fire protection support for storage, distribution and industrial facilities."], ["02", "Commercial buildings", "Configured water and fire-pump systems for expanding urban development."], ["03", "Industrial processing", "Standby-oriented pump packages for plants, workshops and utilities."], ["04", "Water & emergency response", "Mobile pumping and drainage options for temporary transfer needs."]].map(([n,title,text]) => <article key={n}><b>{n}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="section wrap factory"><div className="factory-image"><Image src="https://www.grimmfirepump.com/_next/image?url=%2Fassets%2Ffactory%2Ffactory-assembly.webp&w=1200&q=80" alt="GRIMM PUMP assembly workshop" fill sizes="(max-width: 700px) 100vw, 55vw" /></div><div><p className="eyebrow">THE GRIMM PUMP TEAM</p><h2>Technical clarity before shipment.</h2><p>GRIMM PUMP is the fire-pump systems brand of Grimm Water Treatment (Zhejiang) Co.,Ltd. The global site brings together product data, factory information and direct export contact for project buyers.</p><Link href="/about" className="inline-link">About GRIMM PUMP →</Link></div></section>
  <section className="quote-banner"><div className="wrap"><p className="eyebrow light">PROJECT ENQUIRY</p><h2>Let’s define what your site needs.</h2><p>Share the basic requirement and continue the conversation directly with the GRIMM PUMP team.</p><Link href="/contact" className="cta">Send an enquiry →</Link></div></section>
</>; }
