"use client";
import { FormEvent, useState } from "react";
import type { Lead, Product, NewsArticle } from "@/lib/site-data";
type Tab = "leads" | "products" | "news";
export function AdminConsole({ configured }: { configured: boolean }) { const [password, setPassword] = useState(""); const [loggedIn, setLoggedIn] = useState(false); const [error, setError] = useState(""); const [tab, setTab] = useState<Tab>("leads"); const [leads, setLeads] = useState<Lead[]>([]); const [products, setProducts] = useState<Product[]>([]); const [news, setNews] = useState<NewsArticle[]>([]);
  async function login(event: FormEvent) { event.preventDefault(); const r = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!r.ok) { setError((await r.json() as { error: string }).error); return; } setLoggedIn(true); load("leads"); }
  async function load(next: Tab) { setTab(next); const r = await fetch(`/api/admin/${next}`); if (!r.ok) { setLoggedIn(false); return; } const data = await r.json() as { data: Lead[] | Product[] | NewsArticle[] }; if (next === "leads") setLeads(data.data as Lead[]); if (next === "products") setProducts(data.data as Product[]); if (next === "news") setNews(data.data as NewsArticle[]); }
  async function create(event: FormEvent<HTMLFormElement>, type: "products" | "news") { event.preventDefault(); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form).entries()); const r = await fetch(`/api/admin/${type}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!r.ok) { setError((await r.json() as { error: string }).error); return; } form.reset(); load(type); }
  if (!configured) return <p className="admin-notice">后台尚未配置。请先在 <code>.env.local</code> 设置 <code>ADMIN_PASSWORD</code> 与 <code>ADMIN_SESSION_SECRET</code>，然后重启服务。</p>;
  if (!loggedIn) return <form className="admin-login" onSubmit={login}><h1>非洲站中文管理后台</h1><p>使用本地环境变量中的管理员密码登录。</p><label>管理员密码<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" required /></label><button className="cta">登录 →</button><p className="form-message">{error}</p></form>;
  return <div className="admin-console"><div className="admin-tabs">{(["leads", "products", "news"] as Tab[]).map((item) => <button key={item} className={tab === item ? "selected" : ""} onClick={() => load(item)}>{item === "leads" ? "询盘" : item === "products" ? "产品" : "新闻"}</button>)}<button onClick={async () => { await fetch("/api/admin/logout", { method: "POST" }); setLoggedIn(false); }}>退出</button></div>{tab === "leads" && <section><h1>询盘线索</h1><p>本地提交的客户询盘会持久化在 <code>data/local-site-data.json</code>。</p><div className="admin-table">{leads.length ? leads.map((lead) => <article key={lead.id}><b>{lead.name} · {lead.company}</b><span>{lead.country} · {lead.productInterest}</span><span>{lead.email}</span><p>{lead.message}</p></article>) : <p>暂时没有询盘。</p>}</div></section>}{tab === "products" && <section><h1>产品管理</h1><form className="admin-form" onSubmit={(e) => create(e, "products")}><input name="name" required placeholder="产品名称（英文）" /><select name="category" defaultValue="Fire pump systems"><option>Fire pump systems</option><option>Water supply</option><option>Mobile pumping</option><option>Drainage</option></select><textarea name="summary" required placeholder="产品简介" /><button className="cta">新增并发布产品</button></form><div className="admin-table">{products.map((item) => <article key={item.id}><b>{item.name}</b><span>{item.category}</span><p>{item.summary}</p></article>)}</div></section>}{tab === "news" && <section><h1>新闻管理</h1><p>自动新闻任务尚未启用；接入已审核的可信来源与 API 密钥后再开启。</p><form className="admin-form" onSubmit={(e) => create(e, "news")}><input name="title" required placeholder="新闻标题" /><input name="category" required placeholder="分类，例如 Procurement guide" /><textarea name="excerpt" required placeholder="新闻摘要；不得伪造事实或来源" /><select name="status" defaultValue="draft"><option value="draft">草稿</option><option value="published">发布</option></select><button className="cta">保存新闻</button></form><div className="admin-table">{news.map((item) => <article key={item.id}><b>{item.title}</b><span>{item.category}</span><p>{item.excerpt}</p></article>)}</div></section>}</div>; }
