import Image from "next/image";
import Link from "next/link";
import { ProductCard } from "@/components/product-card";
import { getPublishedProducts } from "@/lib/content-store";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("Fire Pump Systems for African Projects", "Fire pump packages and water systems for African industrial and commercial projects. Final selection is subject to project configuration.", "/");

export default async function Home() {
  const products = await getPublishedProducts();
  const priority = ["edj-fire-pump-set", "diesel-jockey", "long-shaft-fire-pump"];
  const featured = priority.map((id) => products.find((product) => product.id === id)).filter((product): product is NonNullable<typeof product> => Boolean(product));
  return <>
    <section className="hero"><Image src="/images/africa-fire-pump-hero.png" alt="Concept visual of a fire-pump installation serving an African industrial project" fill priority sizes="100vw" className="hero-media" /><div className="hero-shade" /><div className="wrap hero-content"><h1>Fire Pump Systems for African Industrial and Commercial Projects</h1><p>Configured diesel, electric and jockey pump packages for industrial, commercial and infrastructure projects across Africa.</p><div className="hero-actions"><Link href="/contact" className="cta">Discuss your project <span aria-hidden="true">→</span></Link><Link href="/fire-pump-systems" className="ghost-link">View fire pump systems <span aria-hidden="true">→</span></Link></div><div className="hero-facts"><span><b>EDJ · DJ · EJ</b>Complete package options</span><span><b>Project-specific duty</b>Subject to engineering review</span><span><b>Export-focused</b>For African project buyers</span></div></div></section>
    <section className="section intro"><div className="wrap two-column"><div><h2>Start with the realities on site.</h2><p>We help project teams define a fire-pump package around water supply, power availability, duty/standby needs and the documentation required before shipment.</p><Link href="/contact" className="inline-link">Tell us your requirements <span aria-hidden="true">→</span></Link></div><div className="number-list"><article><div><h3>Power-resilient options</h3><p>Electric, diesel and combined configurations for planned and backup operation.</p></div></article><article><div><h3>Project documentation</h3><p>Selection data, catalogues and testing information for engineering review.</p></div></article><article><div><h3>Direct export dialogue</h3><p>Discuss pump selection, delivery scope and your timeline with GRIMM sales.</p></div></article></div></div></section>
    <section className="section wrap"><div className="section-heading"><h2>Fire pump systems first. Project configuration second.</h2><p>Start with EDJ, diesel + jockey and long-shaft fire-pump configurations. Booster and mobile pumping remain available as separate product lines.</p></div><div className="product-grid">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div><Link className="inline-link all-link" href="/products">Explore all products <span aria-hidden="true">→</span></Link></section>
    <section className="section dark"><div className="wrap applications"><div><h2>Built around project conditions, not catalogue pages.</h2><p>Start a procurement conversation with the risk, operating conditions and application your site needs to address.</p><Link href="/applications" className="cta outline">Explore applications <span aria-hidden="true">→</span></Link></div><div className="application-grid">{[["Logistics & warehousing", "Fire protection support for storage, distribution and industrial facilities."], ["Commercial buildings", "Configured water and fire-pump systems for expanding urban development."], ["Industrial processing", "Standby-oriented pump packages for plants, workshops and utilities."], ["Water & emergency response", "Mobile pumping and drainage options for temporary transfer needs."]].map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section wrap factory"><div className="factory-image"><Image src="https://www.grimmfirepump.com/_next/image?url=%2Fassets%2Ffactory%2Ffactory-assembly.webp&w=1200&q=80" alt="GRIMM PUMP assembly workshop" fill sizes="(max-width: 700px) 100vw, 55vw" /></div><div><h2>Technical clarity before shipment.</h2><p>GRIMM PUMP is the fire-pump systems brand of Grimm Water Treatment (Zhejiang) Co.,Ltd. This export site presents product information for African project buyers; final selection and documentation are available on request.</p><Link href="/about" className="inline-link">About GRIMM PUMP <span aria-hidden="true">→</span></Link></div></section>
    <section className="quote-banner"><div className="wrap"><h2>Let’s define what your site needs.</h2><p>Share the basic requirement and continue the conversation directly with the GRIMM PUMP team.</p><Link href="/contact" className="cta">Send an enquiry <span aria-hidden="true">→</span></Link></div></section>
  </>;
}
